django-magic-link/django_magic_login/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^customers/', include("customers.urls")),
    url(r'^admin/', admin.site.urls),
]

sourcelist/urls.py
from django.conf import settings
from django.conf.urls import include, url
# from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    ## general
    url(r'^admin/', admin.site.urls),
    ## patterns from sources app
    # url(r'^sources/', include('sources.urls')),
    url(r'^', include('sources.urls')),
    ## social auth
    url(r'^accounts/login/$', auth_views.LoginView.as_view()),
    # url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include(('social_django.urls', 'social_django'), namespace='social')),
    url('', include(('django.contrib.auth.urls', 'django'), namespace='auth')),
]

# urlpatterns += i18n_patterns(
#     ## patterns from sources app
#     # url(r'^sources/', include('sources.urls')),
#     url(r'^', include('sources.urls')),
# )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

sources/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.urls import path

from sources.views import (
    ConfirmView,
    ContactView,
    PersonDetailView,
    JoinView,
    PageView,
    RedirectSourcesURL,
    # ReportOutdatedView,
    ReportUpdateMineView,
    ReportUpdateView,
    ResultsView,
    SitemapView,
    ThankYouView,
)
from sources.helpers import search_customizations


urlpatterns = [
    ## submission form
    url(r'^confirmation/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        ConfirmView.as_view()),
    # these go before pages with vars in the urls to avoid confusion
    url(r'^join', JoinView.as_view()),
    url(r'^thank-you', ThankYouView.as_view()),
    ## main pages
    url(r'^$', ResultsView.as_view(), name='index'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    # url(r'^report-outdated/$', ReportOutdatedView.as_view()),
    url(r'^report-update-mine/$', ReportUpdateMineView.as_view()),
    url(r'^report-update/$', ReportUpdateView.as_view()),
    url(r'^search/', include('watson.urls', namespace='watson'), search_customizations),
    url(r'^sources/$', RedirectSourcesURL),
    path('<slug:slug>/', PageView.as_view()),
    path('sources/<int:pk>/', PersonDetailView.as_view()),
    path('sources/<slug:slug>/', PersonDetailView.as_view()),
    path('sources/<int:pk>/<slug:slug>/', PersonDetailView.as_view(), name='source'),
    url(r'^sitemap\.xml$', SitemapView.as_view()),
]

sources/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from sources.models import Person


FIELDS_PUBLIC = ['prefix', 'pronouns', 'first_name', 'middle_name', 'last_name', 'type_of_expert', 'title', 'organization', 'website', 'expertise', 'email_address', 'phone_number_primary', 'phone_number_secondary', 'skype', 'twitter', 'language', 'timezone', 'city', 'state', 'country', 'notes', 'media_audio', 'media_text', 'media_video']

MESSAGE_CHOICES = (
    (None, '------'),
    ('general', _('General contact')),
    ('volunteer', _('Volunteer to help')),
    ('share-success', _('Share your succes story')),
    ('request-update', _('Profile update request')),
    ('feature-requset', _('New feature request')),
    ('website-error', _('Website error')),
)

ROLE_CHOICES = (
    (None, '------'),
    ('source', _('Expert')),
    ('journalist', _('Journalist')),
    ('other', _('Other')),
)

REASON_CHOICES = (
    (None, '------'),
    ('inaccurate', 'Inaccurate'),
    ('imposter', 'Imposter'),
    ('offensive', 'Offensive'),
    ('other', 'Other'),
)


class ContactForm(forms.Form):
    name = forms.CharField(required=True, label=_('Your full name'))
    email = forms.EmailField(required=True, label=_('Your email address'))
    message_type = forms.ChoiceField(
        choices=MESSAGE_CHOICES,
        required=True,
        initial='----',
        label=_('I\'m getting in touch because...')
    )
    role = forms.ChoiceField(
        choices=ROLE_CHOICES,
        required=True,
        initial='----',
        label=_('I\'m a...')
    )
    message = forms.CharField(
        required=True,
        widget=forms.Textarea,
        label=_('Message')
    )


class GeneralInfoForm(forms.Form):
    # additional info
    # profile_id = forms.CharField(label=_('Profile ID'), help_text='Must be a number.')  # TODO update to integer after ID + parsing fixed
    profile_id = forms.IntegerField(
        label=_('Profile ID'),
        help_text='Read-only',
        # widget=forms.TextInput(attrs={'readonly':'readonly'}),
        widget=forms.HiddenInput()
    )
    link = forms.URLField(label=_('Link to current information'), help_text='This will help us confirm the details.', required=False)
    explanation = forms.CharField(widget=forms.Textarea, label=_('Explanation/notes'), help_text='What are the updated details?', required=False)
    reason = forms.ChoiceField(choices=REASON_CHOICES)


# class ReportOutdatedForm(GeneralInfoForm, ContactForm):
#     # remove these from ContactForm
#     message = None
#     message_type = None
#     role = None
#     # public fields
#     prefix = forms.BooleanField(label=_('Prefix'), required=False)
#     pronouns = forms.BooleanField(label=_('Pronouns'), required=False)
#     first_name = forms.BooleanField(label=_('First name'), required=False)
#     middle_name = forms.BooleanField(label=_('Middle name'), required=False)
#     last_name = forms.BooleanField(label=_('Last name'), required=False)
#     type_of_expert = forms.BooleanField(label=_('Type of expert'), required=False)
#     title = forms.BooleanField(label=_('Title'), required=False)
#     organization = forms.BooleanField(label=_('Organization'), required=False)
#     website = forms.BooleanField(label=_('Website'), required=False)
#     expertise = forms.BooleanField(label=_('Expertise'), required=False)
#     email_address = forms.BooleanField(label=_('Email address'), required=False)
#     phone_number_primary = forms.BooleanField(label=_('Phone number primary'), required=False)
#     phone_number_secondary = forms.BooleanField(label=_('Phone number secondary'), required=False)
#     skype = forms.BooleanField(label=_('Skype'), required=False)
#     twitter = forms.BooleanField(label=_('Twitter'), required=False)
#     language = forms.BooleanField(label=_('Language'), required=False)
#     timezone = forms.BooleanField(label=_('Timezone'), required=False)
#     city = forms.BooleanField(label=_('City'), required=False)
#     state = forms.BooleanField(label=_('State'), required=False)
#     country = forms.BooleanField(label=_('Country'), required=False)
#     notes = forms.BooleanField(label=_('Notes'), required=False)
#     media_audio = forms.BooleanField(label=_('Media audio'), required=False)
#     media_text = forms.BooleanField(label=_('Media text'), required=False)
#     media_video = forms.BooleanField(label=_('Media video'), required=False)


class SubmitForm(forms.ModelForm):
    # media_field = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=MEDIA_CHOICES) #, verbose_name='Which types of media are you interested interested or experienced in being a source?', help_text='Choose all that apply.')
    required_css_class = 'required'
    error_css_class = 'error'

    class Meta:
        model = Person
        # fields_to_use = FIELDS_PUBLIC
        # fields_to_use.pop(-1)
        # fields_to_use.append('media_field')
        fields = FIELDS_PUBLIC


class ReportUpdateForm(GeneralInfoForm, ContactForm):
    # remove these from ContactForm
    message = None
    message_type = None
    role = None

    field_order = ['reason', 'name', 'email', 'link', 'explanation', 'profile_id']

    # class Meta:
    #     contact_fields = list(ContactForm().fields.keys())
    #     general_fields = list(GeneralInfoForm().fields.keys())
    #     fields = contact_fields + general_fields

    # def __init__(self, *args, **kwargs):
        # super(ReportUpdateForm, self).__init__(*args, **kwargs)
        # self.fields.pop('message')
        # self.fields.pop('message_type')
        # self.fields.pop('role')

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
    <head>
       <meta charset="utf-8">
       <title>{% block title %}{% trans 'Diverse Sources | Science, Health and Environment experts available on deadline' %}{% endblock %}</title>
       <meta name="description" content="Search or join this database of experts to include more underrepresented voices and perspectives in your science, health and environment work.">
       <meta name="keywords" content="science, health, environment, sources, experts, underrepresented, minorities, women">
       <!-- social meta -->
       <meta property="og:image" content="//diversesources.org/static/images/about.jpg" />
       <meta name="twitter:image" content="//diversesources.org/static/images/about.jpg">
       <meta http-equiv="X-UA-Compatible" content="IE=edge">
       <!--    <meta name="viewport" content="width=device-width, initial-scale=1"> -->
       <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
       <meta name="viewport" content="width=device-width, initial-scale=1">
       <link rel="icon" type="image/png" href="/static/images/favicon.ico">
       <!-- Bootstrap core -->
       <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous"> -->
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
       <!-- Bootstrap theme (UPDATE: change to CDN) -->
       <!-- <link rel="stylesheet" type="text/css" href="https://v4-alpha.getbootstrap.com/examples/narrow-jumbotron/narrow-jumbotron.css"> -->
       <!-- jquery -->
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
       <!-- <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/3.3/assets/js/vendor/jquery.min.js"><\/script>')</script> -->
       <!-- Bootstrap JS -->
       <script src="https://getbootstrap.com/docs/3.3/dist/js/bootstrap.min.js"></script>
       <!-- FontAwesome (for icons) -->
       <script src="https://use.fontawesome.com/f953c23132.js"></script>

       <style>

         body {
            /*min-height: 2000px;*/
            padding: 70px 0 70px 0; /* push all content below the fixed-top nav */
         }

          /*  form {
              width: 50%;
              margin: 0 auto;
          }   */

          footer {
            margin-top: 35px;
            bottom: 0;
            width: 100%;
            height: 60px;
            line-height: 60px;
            background-color: #f8f8f8;
          }
          /*
          .social {
            margin: 8px;
          }

          .social a {
            font-size: 18px;
            margin-right: 5px;
            text-decoration: none;
          }

          .social, .social li a {
            display: inline-block;
          }*/

  /*        input {
            width: 200px;
          }
  */
          input,
          label,
          .btn {
              display: block;
          }

          /*  input {
              width: 50%;
          }*/

          input.btn {
              margin-top: 15px;
          }

          select#id_reason {
            margin-bottom: 5px;
          }

          br {
              display: none;
          }

          /*
          .error-list .top li {

          }*/
          .form-fields ul.error-list li {
              color: red;
              /*list-style-type: none;*/
          }

          .g-recaptcha {
              margin-top: 15px;
          }

          .helptext {
              font-size: 80%;
          }

          .main-content {
            width:90%;
            margin: 0 auto;
          }

          textarea {
            width: 250px;
            display: block;
          }

          .nav li {
            font-size: 20px;
          }

          .navbar-brand {
            font-size: 24px;
          }

          .navbar-brand sup {
            font-size: 50%;
          }

          .grouping {
            height: 35px;
          }

          .return-to-db {
            float: left;
          }

          .report-outdated {
            float: left;
            width: 100%;
            margin-bottom: 15px;

          .required::after {
            content: " *";
          }

        </style>
        <!-- CAPTCHA -->
        <script src='https://www.google.com/recaptcha/api.js'></script>

    </head>
    <body>
        <div class="container">
            {% include 'navbar.html' %}
        </div>
        <div class="container">
            {% block main %}{% endblock %}
        </div>
        <div class="container">
            {% include 'footer.html' %}
        </div>
    </body>
    </html>

templates/confirm.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}

<div class="jumbotron">
    {% if success %}
        <h1 class="display-3">{% trans 'Thanks for joining!' %}</h1>
    {% else %}
        <h1 class="display-3">{% trans 'Well, that did not work as expected...' %}</h1>
    {% endif %}
</div>
<div class="main-content lead">
    <p>{{ message }}</p>
</div>

{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}

{% if 'report' in request.path %}
    {% include 'return_links.html' with profile_id=person.id %}
{% endif %}

<div class="jumbotron">
    {% if 'contact' in request.path %}
        <h1 class="display-3">{% trans 'Contact Us' %}</h1>
        <p class="lead">{% trans 'Have a question about this project? Want to help? Let us know!' %}</p>
    {% elif 'report' in request.path %}
        <h1 class="display-3">{% trans 'Report Outdated Profile' %}</h1>
        <p class="lead">{% trans 'Please help us keep the database current. Submit updated information for one or more fields below.' %}</p>
    {% endif %}
</div>
<div class="main-content lead">
    {% if not 'report' in request.path %}
        <p class="explanation">{% trans 'All fields required.' %}</p>
    {% else %}
        {% if person %}
            <p>Submitting for <a href="{% url 'source' pk=person.id slug=person.slug %}">{{ person }}</a>'s profile</p>
        {% endif %}
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        {% if captcha_error %}
        <div class="alert alert-warning alert-dismissible show">
            {% blocktrans %}
                <strong>WARNING</strong>: Please complete the CAPTCHA to submit your form.
            {% endblocktrans %}
        </div>
        {% endif %}
        {{ form.errors }}
        {{ form }}
        <!-- CAPTCHA -->
        <div class="g-recaptcha" data-sitekey="6LdRFU8UAAAAAAKMOt7BIdvNaZnI_2ZLy0j_cFsA"></div>	
        <!-- submit button -->
        <input class="btn btn-primary" type="submit" {% blocktrans %} value="Submit" {% endblocktrans %} />
    </form>
</div>
{% endblock %}

templates/footer.html
{% load i18n %}

<footer class="footer jumbotron" id="footer">
    <div class="container">
    	<p style="margin-top: -30px;">&copy; {% trans 'Diverse Sources' %} {% now 'Y' %}</p>
    </div>
</footer>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-108648804-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-108648804-1');
</script>

templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}

{% endblock %}

templates/join.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
<style>
    label {
        border-top: 15px solid transparent;
    }
    .explanation {
        font-size: 80%;
    }
</style>

<script>
    $(function(){
        // media type field
        var text = {% blocktrans %} "Are you experienced or interested in being a source for the following type of media?" {% endblocktrans %};
        var html = '<h3>' + text + '</h3>';
        $("label[for*='id_media_audio']").before(html);
    });
</script>

<div class="jumbotron">
    <h1 class="display-3">{% trans 'Join the Database' %}</h1>
    <p class="lead">{% trans 'Science, health and environment news stories need a broader set of perspectives. Sign up to be a source for reporters on deadline in this public database.' %}</p>
    <!-- <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p> -->
</div>
<div class="main-content lead">
    <p class="explanation">{% trans 'Required fields are marked with an asterisk (*). All information will be public. Questions? <a href="faqs">Read our FAQs</a>.' %}</p>
    <form action="" method="POST">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                Please correct the following errors below.
            </div>
            <ul class="errorlist top">
                {% for error in form.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="form-fields">
            {{ form }}
        </div>
        <input class="btn btn-primary" type="submit" {% blocktrans %} value="Submit" {% endblocktrans %} />
    </form>
</div>
{% endblock %}

templates/navbar.html
{% load i18n %}
{% load sources_extras %}
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">{% trans 'Toggle navigation' %}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">{% trans 'Diverse Sources' %} <sup>BETA</sup><!-- {{ site_name }} --></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Home</a></li> -->
        <li><a href="/join">{% trans 'Join' %}</a></li>
        <li><a href="/about">{% trans 'About' %}</a></li>
        <li><a href="/contact">{% trans 'Contact' %}</a></li>
        {# <li><a href="mailto:?bcc={% invite_bcc '' %}&subject={% invite_subject '' %}&body={% invite_body '' %}">{% trans 'Invite' %}</a> #}
        </li>
      {% if donate_url %}
        <li><a href="{{ donate_url }}" target="_blank">{% trans 'Donate' %}</a></li>
      {% endif %}
      </ul>
    <div class="nav navbar-nav navbar-right">
      <ul class="nav navbar-nav" style="float:left;">
        {% include "social-icons.html" %}
      </ul>
      <form action="{% url 'watson:search' %}" class="nav navbar-form" style="float:left;">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Find sources" name="q" value="{{request.GET.q}}">
          <input type="submit" value="Go" class="btn btn-default" style="float:right; margin:0px 0px 0px 10px;">
        </div>
      </form>
    </div>
      <!-- <ul class="nav navbar-nav navbar-right">
        <li><a href="../navbar/">Default</a></li>
        <li><a href="../navbar-static-top/">Static top</a></li>
        <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
      </ul> -->
    </div><!--/.nav-collapse -->
  </div>
</nav>

templates/report_update.html
{% load i18n %}

<div class="report-outdated dropdown btn-group">
  <button type="button" class="btn btn-default dropdown-toggle btn-primary" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
    {% if 'report' in request.path %}
      {% trans 'Choose a different report' %}
    {% else %}
      <span class="glyphicon glyphicon-flag"></span>
      {% trans 'Report outdated profile' %}
    {% endif %}
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <li><a class="dropdown-item" href="/report-update-mine?id={{ profile_id }}">{% trans 'Update your profile' %}</a></li>
    <li><a class="dropdown-item" href="/report-update?id={{ profile_id }}">{% trans "Update someone else's profile" %}</a></li>
    {% comment %}
    <li><a class="dropdown-item" href="/report-outdated?id={{ profile_id }}">{% trans 'Report outdated information' %}</a></li>
    {% endcomment %}
  </ul>
</div>

templates/results.html
{% extends 'base.html' %}
{% load i18n %}
{% load sources_extras %}
{% load watson %}

{% block main %}

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"/>

<script type="text/javascript" src="https://cdn.datatables.net/r/bs-3.3.5/jqc-1.11.3,dt-1.10.10/datatables.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>

<script type="text/javascript">
    $(document).ready(function(){
        /* setup and customize data tables plugin */
        $("#sources").DataTable({
            responsive: true, 
            details: true,
            "order": [[ 1, "asc" ]],
            stateSave: true,
            "language": {
                "search": "Filter results:"
            }
            // "columns":
            //     { "width": "20%" },
            //     null,
            //     null,
            //     null,
            //     null
            // ]
        });
    });
</script>
<div class="jumbotron">
    <h1 class="display-3">{% trans 'Find Sources' %}</h1>
    <p class="lead">
        {% blocktrans %}
            Search or <a href="/join">join</a> this database of experts to include more underrepresented voices and perspectives in your science, health and environment work on deadline.
        {% endblocktrans %}
</p>
</div>
{% if results.count == 0 %}
    <p class="leader">{% trans 'Sources coming soon!' %}</p>
{% else %}
<div class="main-content">
    <!-- START SEARCH -->
    <h1>{% if query %}Search results for &ldquo;{{query}}&rdquo;{% endif %}</h1>
    {% if search_results %}
        <table id="sources" class="display responsive stripe lead" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>{% trans 'First name' %}</th>
                    <th>{% trans 'Last name' %}</th>
                    <th>{% trans 'Type of expert' %}</th>
                    <th>{% trans 'Expertise' %}</th>
                    <th>{% trans 'Organization' %}</th>
                    <th>{% trans 'Language(s)' %}</th>
                    <th>{% trans 'Time zone' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for search_result in search_results %}
                    <tr>
                        <td>
                            <a href="{{ search_result.url }}">
                                {{ search_result.object.first_name }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ search_result.url }}">
                                {{ search_result.object.last_name }}
                            </a>
                        </td>
                        <td>{{ search_result.object.type_of_expert }}</td>
                        <td>{{ search_result.object.expertise }}</td>
                        <td>{{ search_result.object.organization }}</td>
                        <td>{{ search_result.object.language }}</td>
                        <td>{{ search_result.object.timezone|timezone_format }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        {% if query %}
            <p><em>There are no results to display.</em></p>
            <p><em>Try entering less specific search terms.</em></p>
        {% else %}
            <!-- START default view -->
            <table id="sources" class="display responsive stripe lead" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>{% trans 'First name' %}</th>
                        <th>{% trans 'Last name' %}</th>
                        <th>{% trans 'Type of expert' %}</th>
                        <th>{% trans 'Expertise' %}</th>
                        <th>{% trans 'Organization' %}</th>
                        <th>{% trans 'Language(s)' %}</th>
                        <th>{% trans 'Time zone' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for result in results %}
                        <tr>
                            <td>
                                <a href="{% url 'source' slug=result.slug pk=result.id %}">
                                    {{ result.first_name }}
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'source' slug=result.slug pk=result.id %}">
                                    {{ result.last_name }}
                                </a>
                            </td>
                            <td>{{ result.type_of_expert }}</td>
                            <td>{{ result.expertise }}</td>
                            <td>{{ result.organization }}</td>
                            <td>{{ result.language }}</td>
                            <td>{{ result.timezone|timezone_format }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <!-- END default view -->
        {% endif %}
    {% endif %}
    <!-- END SEARCH -->
</div>
{% endif %}
{% endblock %}

templates/return_links.html
{% load i18n %}

<div class="grouping">
    <div class="return-to-db">
        <p><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            {% if 'report' in request.path %}
                <a href="{% url 'source' pk=person.id slug=person.slug %}"> {% trans 'Return to profile' %}</a>
            {% elif '?' in request.META.HTTP_REFERER %}
                <a href="{{ request.META.HTTP_REFERER }}"> {% trans 'Return to results' %}</a>
            {% else %}
                <a href="/"> {% trans 'Return to database' %}</a>
            {% endif %}
        </p>
    </div>
</div>

templates/search-form.html
{% load i18n %}

<form id="searchform" action="{% url 'search' %}" method="get" accept-charset="utf-8">
  <button class="searchbutton" type="submit">
    <i class="fa fa-search"></i>
  </button>
  <input class="searchfield" id="searchbox" name="q" type="text" placeholder="{% trans 'Search' %}">
</form>

templates/search.html
{% load i18n %}
<form id="searchform" action="{% url 'search' %}" method="get" accept-charset="utf-8">
  <button class="searchbutton" type="submit">
    <i class="fa fa-search"></i>
  </button>
  <input class="searchfield" id="searchbox" name="q" type="text" placeholder="{% trans 'Search' %}">
</form>

templates/submit.html
{% extends 'base.html' %}

{% block main %}
<style>

/*  form {
        width: 50%;
        margin: 0 auto;
    }   */

    input,
    label, .btn {
        display: block;
    }

/*  input {
        width: 50%;
    }*/

    input.btn {
        margin-top: 15px; 
    }

    br {
        display: none;
    }

    .helptext {
        font-size: 60%;
    }

/*  :required {
        font-weight: bold;
    }*/

</style>
<div class="jumbotron">
    <h1 class="display-3">Join the database</h1>
    <p class="lead">Science, health and environment news stories need a broader set of perspectives. Sign up to be a source for reporters on deadline.</p>
    <!-- <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p> -->
</div>
<div class="">
    <form action="" method="POST">
        {% csrf_token %}
        <!-- {{ form.errors }} -->
        {{ form }}
        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
</div>
{% endblock %}

templates/thank-you.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}

    <div class="jumbotron">
        <h1 class="display-3">{% trans 'Thank you!' %}</h1>
    </div>

    {% if previous == 'report-update-mine' %}
        <p>{% trans 'Please check your email for a message that includes a link to update your profile.' %}</p>
        <p>{% trans 'If you no longer have access to that email account or have any other questions, please ' %}<a href="{% url 'contact' %}">{% trans 'contact us' %}</a>.</p>
    {% elif previous == 'report-update' %}
        <p>{% trans 'We will will review your report as soon as possible and contact you if we have any follow up questions.' %}</p>
    {% elif previous == 'join' %}
        <p>{% trans 'Please check your email and confirm your profile for it to appear on the site.' %}</p>
    {% elif existing %}
        <p>{% trans 'Your profile already exists. If you need to change any details, search your email for the initial message and click on the link to update the profile.' %} <!-- To request a new email be sent with your current details and link to edit, click here. --></p>
    {% endif %}

{% endblock %}